# Generated by Django 5.2.4 on 2025-09-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtask',
            name='priority',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
