# Generated by Django 5.2.3 on 2025-07-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0002_task_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
