# Generated by Django 5.2.4 on 2025-09-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_addtask_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtask',
            name='date_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='addtask',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='addtask',
            name='status',
            field=models.CharField(blank=True, default='Today', max_length=20, null=True),
        ),
    ]
