# Generated by Django 5.2.4 on 2025-09-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_addtask_date_time_alter_addtask_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtask',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='addtask',
            name='is_delete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
