# Generated by Django 5.2.3 on 2025-07-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0003_task_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="complete",
            field=models.CharField(
                choices=[("uncomplete", "uncomplete"), ("complete", "complete")]
            ),
        ),
    ]
