# Generated by Django 5.2.4 on 2025-07-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0004_alter_task_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_register",
            name="password",
            field=models.CharField(max_length=10),
        ),
    ]
