# Generated by Django 5.2.4 on 2025-07-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0005_alter_user_register_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_register",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
