# Generated by Django 5.2.4 on 2025-07-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0006_alter_user_register_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="titel",
            new_name="Task",
        ),
        migrations.AlterField(
            model_name="task",
            name="complete",
            field=models.CharField(
                choices=[("uncomplete", "uncomplete"), ("complete", "complete")],
                default="uncomplete",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="date_time",
            field=models.DateField(),
        ),
    ]
