# Generated by Django 5.2.4 on 2025-08-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0007_rename_titel_task_task_alter_task_complete_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="complete",
            field=models.CharField(
                auto_created=True,
                choices=[("uncomplete", "uncomplete"), ("complete", "complete")],
                default="uncomplete",
            ),
        ),
    ]
